steps:
  - uses: ros-tooling/setup-ros@v0.6
    with:
      required-ros-distributions: humble
  - uses: ros-tooling/action-ros-ci@v0.3
    with:
      package-name: my_package
      target-ros2-distro: humble
